# Generated by Django 3.2.3 on 2021-05-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinepizzas', '0002_position_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4)),
            ],
            options={
                'db_table': 'drink',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4)),
            ],
            options={
                'db_table': 'snack',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pizza',
            name='mass',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
