# Generated by Django 3.2.3 on 2021-05-15 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinepizzas', '0003_auto_20210515_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=12, unique=True)),
                ('email', models.TextField()),
                ('productType', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='text',
            field=models.TextField(default='FeedBack'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlinepizzas.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='onlinepizzas.product')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='onlinepizzas.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='DistributorOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('estimatedDate', models.DateField()),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('orderStatus', models.CharField(max_length=50)),
                ('lastDeliveryDate', models.DateField()),
                ('orderContent', models.TextField()),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='onlinepizzas.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='DecommissionedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('dateOfDecommission', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='onlinepizzas.product')),
            ],
        ),
    ]
