# Generated by Django 3.2.3 on 2021-05-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinepizzas', '0005_auto_20210515_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField(default=1)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinepizzas.drink')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinepizzas.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField(default=1)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinepizzas.pizza')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinepizzas.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSnack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField(default=1)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinepizzas.snack')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinepizzas.order')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
